import { Enum } from 'enum-plus'

export const ErrorEnum = Enum({
  USER_NOT_FOUND_ERROR: { value: 'UserNotFoundError', label: '用户不存在' },
  ACCOUNT_OR_EMAIL_EXIST_ERROR: { value: 'AccountOrEmailExistError', label: '账号或邮箱已存在' },
  ACCOUNT_OR_PASSWORD_ERROR: { value: 'AccountOrPasswordError', label: '账号或密码错误' },
  CAPTCHA_ERROR: { value: 'CaptchaError', label: '验证码错误' },
  PASSWORD_NOT_MATCH_ERROR: { value: 'PasswordNotMatchError', label: '密码不匹配' },
  TOKEN_EXPIRED_ERROR: { value: 'TokenExpiredError', label: '过期签名' },
  JSON_WEB_TOKEN_ERROR: { value: 'JsonWebTokenError', label: '无效签名' },
  NOT_BEFORE_ERROR: { value: 'NotBeforeError', label: '未到生效时间' },
  AUTHORIZATION_NOT_EXIST_ERROR: { value: 'AuthorizationNotExistError', label: 'Authorization 不存在' },
  AUTHORIZATION_FORMAT_ERROR: { value: 'AuthorizationFormatError', label: 'Authorization 格式错误' },
  FORBIDDEN_ERROR: { value: 'ForbiddenError', label: '没有权限访问' },
  CONFIG_EXIST_ERROR: { value: 'ConfigExistError', label: '配置已存在' },
  CONFIG_NOT_FOUND_ERROR: { value: 'ConfigNotFoundError', label: '配置不存在' },
  DEPT_EXIST_ERROR: { value: 'DeptExistError', label: '部门已存在' },
  DEPT_NOT_FOUND_ERROR: { value: 'DeptNotFoundError', label: '部门不存在' },
  DICT_VALUE_EXIST_ERROR: { value: 'DictValueExistError', label: '字典值已存在' },
  DICT_VALUE_NOT_FOUND_ERROR: { value: 'DictValueNotFoundError', label: '字典值不存在' },
  DICT_TYPE_EXIST_ERROR: { value: 'DictTypeExistError', label: '字典类型已存在' },
  DICT_TYPE_NOT_FOUND_ERROR: { value: 'DictTypeNotFoundError', label: '字典类型不存在' },
  LANG_EXIST_ERROR: { value: 'LangExistError', label: '语言翻译已存在' },
  LANG_NOT_FOUND_ERROR: { value: 'LangNotFoundError', label: '语言翻译不存在' },
  MENU_EXIST_ERROR: { value: 'MenuExistError', label: '菜单已存在' },
  MENU_NOT_FOUND_ERROR: { value: 'MenuNotFoundError', label: '菜单不存在' },
  POST_EXIST_ERROR: { value: 'PostExistError', label: '岗位已存在' },
  POST_NOT_FOUND_ERROR: { value: 'PostNotFoundError', label: '岗位不存在' },
  ROLE_EXIST_ERROR: { value: 'RoleExistError', label: '角色已存在' },
  ROLE_NOT_FOUND_ERROR: { value: 'RoleNotFoundError', label: '角色不存在' },
} as const)
