allowBuilds:
  "@nestjs/core": true
  "@scarf/scarf": true
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - "@cj-tech-master/excelts@9.6.1"
  - "@scalar/client-side-rendering@0.2.2"
  - "@scalar/helpers@0.8.2"
  - "@scalar/nestjs-api-reference@1.2.2"
  - "@scalar/schemas@0.4.2"
  - "@scalar/types@0.13.2"
  - "@scalar/client-side-rendering@0.2.3"
  - "@scalar/nestjs-api-reference@1.2.3"
  - "@scalar/schemas@0.4.3"
  - "@scalar/types@0.13.3"
  - element-plus@2.14.2
  - es-toolkit@1.47.1
  - "@cj-tech-master/excelts@10.2.0"
  - eslint@10.5.0
  - '@nestjs/common@11.1.27'
  - '@nestjs/core@11.1.27'
  - '@nestjs/platform-fastify@11.1.27'
  - '@oxc-project/runtime@0.136.0'
  - axios@1.18.0
  - '@scalar/client-side-rendering@0.2.4'
  - '@scalar/nestjs-api-reference@1.2.4'
  - '@scalar/schemas@0.5.0'
  - '@scalar/types@0.14.0'
  - '@bull-board/api@8.0.1'
  - '@bull-board/fastify@8.0.1'
  - '@bull-board/nestjs@8.0.1'
  - '@bull-board/ui@8.0.1'
  - '@intlify/core-base@11.4.6'
  - '@intlify/devtools-types@11.4.6'
  - '@intlify/message-compiler@11.4.6'
  - '@intlify/shared@11.4.6'
  - '@nestjs-modules/mailer@2.3.7'
  - '@oxc-project/runtime@0.137.0'
  - bullmq@5.79.0
  - vue-i18n@11.4.6
  - uuid@14.0.1
  - bullmq@5.79.1
  - enum-plus@3.2.0
  - bullmq@5.80.2
