allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@rolldown/binding-android-arm-eabi@1.2.5'
  - '@rolldown/binding-android-arm64@1.2.5'
  - '@rolldown/binding-darwin-arm64@1.2.5'
  - '@rolldown/binding-darwin-x64@1.2.5'
  - '@rolldown/binding-freebsd-x64@1.2.5'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.5'
  - '@rolldown/binding-linux-arm64-gnu@1.2.5'
  - '@rolldown/binding-linux-arm64-musl@1.2.5'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.5'
  - '@rolldown/binding-linux-s390x-gnu@1.2.5'
  - '@rolldown/binding-linux-x64-gnu@1.2.5'
  - '@rolldown/binding-linux-x64-musl@1.2.5'
  - '@rolldown/binding-openharmony-arm64@1.2.5'
  - '@rolldown/binding-win32-arm64-msvc@1.2.5'
  - '@rolldown/binding-win32-x64-msvc@1.2.5'
  - '@xlt-token/core@2.1.1'
  - '@xlt-token/jwt@2.1.1'
  - '@xlt-token/nestjs@2.1.1'
  - '@xlt-token/store-redis@2.1.1'
  - mysql2@3.23.4
  - rolldown@1.2.5
  - vite@8.2.2
