/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Nitro Template - version 1.0
 *
 * Nitro 模板接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'Auth.login': ['POST', '/api/auth/login'],
  'Auth.logout': ['POST', '/api/auth/logout'],
  'Captcha.image': ['GET', '/api/captcha/image'],
  'CurrentUser.getInfo': ['GET', '/api/current-user/info'],
  'CurrentUser.getProfile': ['GET', '/api/current-user/profile'],
  'CurrentUser.updateProfile': ['POST', '/api/current-user/update-profile'],
  'CurrentUser.updatePassword': ['POST', '/api/current-user/update-password'],
  'MonitorCache.findPage': ['POST', '/api/monitor/cache/findPage'],
  'MonitorCache.remove': ['DELETE', '/api/monitor/cache/remove'],
  'MonitorCache.clear': ['DELETE', '/api/monitor/cache/clear'],
  'MonitorOnline.findPage': ['POST', '/api/monitor/online/findPage'],
  'MonitorOnline.remove': ['DELETE', '/api/monitor/online/remove'],
  'MonitorOperate.findPage': ['POST', '/api/monitor/operate/findPage'],
  'SystemConfig.create': ['POST', '/api/system/config/create'],
  'SystemConfig.findByKey': ['GET', '/api/system/config/findByKey'],
  'SystemConfig.findPage': ['POST', '/api/system/config/findPage'],
  'SystemConfig.remove': ['DELETE', '/api/system/config/remove'],
  'SystemConfig.update': ['POST', '/api/system/config/update'],
  'SystemConfig.export': ['POST', '/api/system/config/export'],
  'SystemDept.create': ['POST', '/api/system/dept/create'],
  'SystemDept.findList': ['POST', '/api/system/dept/findList'],
  'SystemDept.remove': ['DELETE', '/api/system/dept/remove'],
  'SystemDept.update': ['POST', '/api/system/dept/update'],
  'SystemDictType.create': ['POST', '/api/system/dict/type/create'],
  'SystemDictType.findByKey': ['GET', '/api/system/dict/type/findByKey'],
  'SystemDictType.findPage': ['POST', '/api/system/dict/type/findPage'],
  'SystemDictType.remove': ['DELETE', '/api/system/dict/type/remove'],
  'SystemDictType.update': ['POST', '/api/system/dict/type/update'],
  'SystemDictType.export': ['POST', '/api/system/dict/type/export'],
  'SystemDictData.create': ['POST', '/api/system/dict/data/create'],
  'SystemDictData.findList': ['POST', '/api/system/dict/data/findList'],
  'SystemDictData.remove': ['DELETE', '/api/system/dict/data/remove'],
  'SystemDictData.update': ['POST', '/api/system/dict/data/update'],
  'SystemDictData.export': ['POST', '/api/system/dict/data/export'],
  'SystemLang.create': ['POST', '/api/system/lang/create'],
  'SystemLang.findAll': ['GET', '/api/system/lang/findAll'],
  'SystemLang.findByKey': ['GET', '/api/system/lang/findByKey'],
  'SystemLang.findPage': ['POST', '/api/system/lang/findPage'],
  'SystemLang.remove': ['POST', '/api/system/lang/remove'],
  'SystemLang.update': ['POST', '/api/system/lang/update'],
  'SystemMenu.create': ['POST', '/api/system/menu/create'],
  'SystemMenu.findList': ['POST', '/api/system/menu/findList'],
  'SystemMenu.remove': ['DELETE', '/api/system/menu/remove'],
  'SystemMenu.update': ['POST', '/api/system/menu/update'],
  'SystemPost.create': ['POST', '/api/system/post/create'],
  'SystemPost.findPage': ['POST', '/api/system/post/findPage'],
  'SystemPost.remove': ['DELETE', '/api/system/post/remove'],
  'SystemPost.update': ['POST', '/api/system/post/update'],
  'SystemPost.export': ['POST', '/api/system/post/export'],
  'SystemPostAuth.allocateUser': ['POST', '/api/system/post/auth/allocateUser'],
  'SystemPostAuth.findAllocatedUserPage': ['POST', '/api/system/post/auth/findAllocatedUserPage'],
  'SystemPostAuth.findUnallocatedUserPage': ['POST', '/api/system/post/auth/findUnallocatedUserPage'],
  'SystemPostAuth.unallocateUser': ['POST', '/api/system/post/auth/unallocateUser'],
  'SystemRole.create': ['POST', '/api/system/role/create'],
  'SystemRole.findPage': ['POST', '/api/system/role/findPage'],
  'SystemRole.remove': ['DELETE', '/api/system/role/remove'],
  'SystemRole.update': ['POST', '/api/system/role/update'],
  'SystemRole.export': ['POST', '/api/system/role/export'],
  'SystemRoleAuth.allocateUser': ['POST', '/api/system/role/auth/allocateUser'],
  'SystemRoleAuth.findAllocatedUserPage': ['POST', '/api/system/role/auth/findAllocatedUserPage'],
  'SystemRoleAuth.findUnallocatedUserPage': ['POST', '/api/system/role/auth/findUnallocatedUserPage'],
  'SystemRoleAuth.unallocateUser': ['POST', '/api/system/role/auth/unallocateUser'],
  'SystemRoleMenu.assign': ['POST', '/api/system/role/menu/assign'],
  'SystemRoleMenu.assigned': ['POST', '/api/system/role/menu/assigned'],
  'SystemUser.create': ['POST', '/api/system/user/create'],
  'SystemUser.findPage': ['POST', '/api/system/user/findPage'],
  'SystemUser.remove': ['DELETE', '/api/system/user/remove'],
  'SystemUser.update': ['POST', '/api/system/user/update'],
  'SystemUser.export': ['POST', '/api/system/user/export'],
  'SystemUser.exportTemplate': ['POST', '/api/system/user/exportTemplate'],
  'SystemUser.importTemplate': ['POST', '/api/system/user/importTemplate']
};
